items:
  - name: dance_of_death
    cost: 3300
    health_stats:
      max_health: {}
      current_health: {}
      growth_rate: {}
      regeneration: {}
    mana_stats:
      max_mana: {}
      current_mana: {}
      regeneration: {}
    attack_stats:
      attack_damage: 60.0
    defense_stats:
      armor: 50.0
      magic_resistance: {}
    speed_stats:
      attack_speed: {}
      ability_haste: 15.0
      movement_speed: {}
    # 크리티컬
    crit_chance: {}
    crit_damage: {}
    # 관통력
    armor_penetration: {}
    magic_penetration: {}
    # 흡혈
    life_steal: {}  # 생명력 흡수
    physical_vamp: {} # 물리 피해 흡혈
    omnivamp: {}  # 모든 피해 흡혈
    spell_vamp: {}  # 주문 흡혈
    # 기타
    range: {}    # 사거리
    tenacity: {}   # 강인함
    heal_and_shield_power: {}  # 회복 및 보호막 효과